# Generated by Django 5.2.6 on 2026-08-31 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_comparisons', to='documents.document')),
                ('target_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_comparisons', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('changed', 'Changed'), ('matched', 'Matched'), ('missing', 'Missing')], max_length=20)),
                ('difference_explanation', models.TextField(blank=True, null=True)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_clause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_comparison_results', to='documents.clause')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='comparison.comparison')),
                ('target_clause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_comparison_results', to='documents.clause')),
            ],
            options={
                'db_table': 'comparison_results',
                'ordering': ['created_at'],
            },
        ),
    ]
