# Generated by Django 5.2.6 on 2026-08-31 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='base_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_comparisons', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='target_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_comparisons', to='documents.document'),
        ),
    ]
