# Generated by Django 5.2.6 on 2026-08-31 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_reference', models.CharField(max_length=512)),
                ('document_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('extracting', 'Extracting'), ('ocr', 'OCR Processing'), ('segmenting', 'Segmenting'), ('classifying', 'Classifying'), ('simplifying', 'Simplifying'), ('summarizing', 'Summarizing'), ('indexing', 'Indexing'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='queued', max_length=50)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('original_text', models.TextField()),
                ('simplified_text', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low'), ('safe', 'Safe')], db_index=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('Payment', 'Payment'), ('Termination', 'Termination'), ('Renewal', 'Renewal'), ('Confidentiality', 'Confidentiality'), ('Liability', 'Liability'), ('Intellectual Property', 'Intellectual Property'), ('Privacy', 'Privacy'), ('Dispute Resolution', 'Dispute Resolution')], db_index=True, max_length=50, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('rule_findings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='documents.document')),
            ],
            options={
                'db_table': 'clauses',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose_text', models.TextField(blank=True, null=True)),
                ('obligations_text', models.TextField(blank=True, null=True)),
                ('key_terms_text', models.TextField(blank=True, null=True)),
                ('key_risks_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='documents.document')),
            ],
            options={
                'db_table': 'document_summaries',
            },
        ),
    ]
