# Generated by Django 5.2.17 on 2026-09-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clause',
            name='risk_source',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clause',
            name='structured_explanation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
